### ISSUE TITLE
make Design Document pdf

### ISSUE THREAD

**Issue by Alexey-N-Chernyshov** [Alexey-N-Chernyshov/INPLS-SED-2017-g03#14]
1. Study
http://messir.uni.lu:8090/confluence/display/TEACH/Design+Document
https://www.dropbox.com/sh/ghnbnz77s9q87c3/AADYCFoydTH58naxTEwsbAMMa/SED-iCrash.FX-slides.pdf?dl=0
2. Download and build template

**Comment by mitrx** [comment]
spent 10m
