### ISSUE TITLE
Fill in the SWEBOK

### ISSUE THREAD

**Issue by Alexey-N-Chernyshov** [Alexey-N-Chernyshov/INPLS-SED-2017-g03#2]
Fill the SWEBOK coverage excel file
get here
https://www.dropbox.com/sh/mltzcr6ngxji0e8/AADFF-iFoKZFMoXxa2ksPVFya/general/swebok?dl=0

put here
https://www.dropbox.com/home/G03/SWEBOK

**Comment by Alexey-N-Chernyshov** [comment]
took 1h

**Comment by ali-dzhamal** [comment]
took 1 h

**Comment by mitrx** [comment]
spent 1h 16m
