### ISSUE TITLE
write Authentication (SMS based) feature description

### ISSUE THREAD

**Issue by Alexey-N-Chernyshov** [Alexey-N-Chernyshov/INPLS-SED-2017-g03#27]
In addition to the login/Password based authentication should be adapted in order to provide a SMS based authentication.

Users are Coordinators and Administrators should provide her/his phone number of an SMS compatible device to Administrator. Administrator inputs phone number during registration of users.
On the authentication panel after authentication with login/password user should enter temporary code.
Temporary code is an 6-letter message generated by iCrash and delivered with Communication Company to the user.
Lifetime of temporary code is 180 sec (configurable).
Readability of temporary code. It should be 6 letters with well recognizable symbols (e.g. there should be no 0 and O, l or I or 1 in one message) (configurable).
In case the temporary code and the code generated by iCrash system match the user gets authenticated, otherwise the authentication is failed and the user have to begin authentication process from the first step.

3. Usage Guide
4. Software operations
5. Error messages

mock up

**Comment by Alexey-N-Chernyshov** [comment]
p 3. done 46 min

**Comment by mitrx** [comment]
p 3. done, spent 45m

**Comment by ali-dzhamal** [comment]
p. 3 done 45 min

**Comment by Alexey-N-Chernyshov** [comment]
all done
total +5h
